/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "shingles_constants.h"



const shinglesConstants g_shingles_constants;

shinglesConstants::shinglesConstants() {
}



