/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef shingles_CONSTANTS_H
#define shingles_CONSTANTS_H

#include "shingles_types.h"



class shinglesConstants {
 public:
  shinglesConstants();

};

extern const shinglesConstants g_shingles_constants;



#endif
